import type { Locale } from '@/lib/i18n'

const en = {
  nav: { home: 'Home', project: 'Project', research: 'Research', about: 'About' },
  menu: 'Menu',
  city: 'Sarajevo',
  studio: 'Nova Forma',
  home: {
    title: ['Shaping', 'The Form', 'of Light'],
    lead: 'Nova Forma creates light-led projects for people and brands seeking a new form. Based in Sarajevo, working worldwide.',
    projects: 'Projects',
    whatWeDo: 'What we do',
    statement: 'Nova Forma is a creative studio based in Sarajevo.\nWe give ideas a new form through light and space.',
    aboutUs: 'About us',
    featured: 'Featured project\nand research',
    viewAll: 'View all project',
  },
  territory: 'Our territory\nand fields',
  fieldsA: ['Space', 'Produce', 'Direction', 'Design', 'Branding', 'Technology', 'Film'],
  fieldsB: ['Architecture', 'Education', 'Food', 'Music', 'Fashion', 'Culture', 'Hospitality', 'Beauty', 'Heritage'],
  footer: {
    tagline: 'Based in Sarajevo\nworking worldwide',
    backToTop: 'Back to top',
    cta: 'Get *in* touch',
    social: 'Instagram',
    dark: 'Dark mode',
    light: 'Light mode',
  },
  archive: { drag: '(Drag)', swipe: '(Swipe)' },
  cursor: { drag: 'Drag', explore: 'Explore', next: 'Next', click: 'Click' },
  detail: {
    back: 'Back',
    scroll: '(Scroll)',
    next: 'Next',
    client: 'Client',
    year: 'Year',
    category: 'Category',
    link: 'Link',
    visit: 'Visit site',
    shiftThe: 'Form the',
    credits: 'Credits',
    awards: 'Awards',
    awardsText: 'Awwwards Site of the Day — CSS Design Awards Best UI — European Design Awards Shortlist',
    nextProject: 'Next\nproject',
  },
  research: {
    title: ['Always', 'Exploring'],
    support: 'What is forming and\nwhat can be formed',
  },
  about: {
    title: ['About', 'Nova Forma'],
    support: 'Created for the things\nand people seeking a new form',
    concept: 'Concept',
    statement: 'We believe every idea already has a shape.\nOur work is to find it, give it light\nand let people step inside.',
    conceptBody:
      'Nova Forma is a studio of designers, engineers and storytellers working between the physical and the digital. We started in a small room above a Baščaršija workshop, surrounded by copper, stone and patience. That heritage still guides us: we prototype by hand, we test with light, and we only call a project finished when it feels inevitable. Today we work with brands, cultural institutions and cities around the world.',
    logoLead:
      'The logo re-forms itself every midnight, based on the year, month and date. It carries the Nova Forma idea that nothing we make stays still, just like the people and places we design for.',
    nextForm: 'Next form',
    formThe: ['Form', 'Light', 'Space', 'Motion', 'Memory'],
    team: 'Team',
    collaborator: 'Collaborator',
    open: 'Open',
    close: 'Close',
    gallery: 'Gallery',
    join: 'Join us',
    joinBody:
      'We are always looking for curious people who enjoy making things with their hands and their heads. If you like light, space and slow craft, write to us with a few projects that make you proud.',
    entry: 'Entry',
    roles: ['Spatial designer', '3D artist', 'Creative developer', 'Producer'],
    profile: 'Profile',
    profileRows: [
      ['Company name', 'Nova Forma d.o.o.'],
      ['Representative', 'Amar Hadžić'],
      ['Office', 'Ferhadija 12, 71000 Sarajevo\nBosnia and Herzegovina'],
      ['Fields', 'Spatial design, branding, 3D, film, digital experiences, research'],
      ['Clients', 'Maison Aura, Vedra Watches, Pulse Labs, Hotel Bašta, BH Aviation Museum'],
    ],
    partners: 'Partners',
    partner: 'Atelier Svjetlo',
    partnerDesc: 'Lighting engineering partner',
  },
}

export type Dict = typeof en

const bs: Dict = {
  nav: { home: 'Početna', project: 'Projekti', research: 'Istraživanje', about: 'O nama' },
  menu: 'Meni',
  city: 'Sarajevo',
  studio: 'Nova Forma',
  home: {
    title: ['Oblikujemo', 'Formu', 'Svjetla'],
    lead: 'Nova Forma stvara projekte vođene svjetlom za ljude i brendove koji traže novu formu. Iz Sarajeva, za cijeli svijet.',
    projects: 'Projekti',
    whatWeDo: 'Šta radimo',
    statement: 'Nova Forma je kreativni studio iz Sarajeva.\nIdejama dajemo novu formu kroz svjetlo i prostor.',
    aboutUs: 'O nama',
    featured: 'Izdvojeni projekti\ni istraživanja',
    viewAll: 'Svi projekti',
  },
  territory: 'Naše teritorije\ni oblasti',
  fieldsA: ['Prostor', 'Produkcija', 'Režija', 'Dizajn', 'Brending', 'Tehnologija', 'Film'],
  fieldsB: ['Arhitektura', 'Edukacija', 'Hrana', 'Muzika', 'Moda', 'Kultura', 'Ugostiteljstvo', 'Ljepota', 'Naslijeđe'],
  footer: {
    tagline: 'Iz Sarajeva\nza cijeli svijet',
    backToTop: 'Na vrh',
    cta: 'Javite *nam* se',
    social: 'Instagram',
    dark: 'Tamna tema',
    light: 'Svijetla tema',
  },
  archive: { drag: '(Prevuci)', swipe: '(Prevuci)' },
  cursor: { drag: 'Prevuci', explore: 'Istraži', next: 'Dalje', click: 'Klik' },
  detail: {
    back: 'Nazad',
    scroll: '(Skrolaj)',
    next: 'Dalje',
    client: 'Klijent',
    year: 'Godina',
    category: 'Kategorija',
    link: 'Link',
    visit: 'Posjeti stranicu',
    shiftThe: 'Oblikuj',
    credits: 'Zasluge',
    awards: 'Nagrade',
    awardsText: 'Awwwards Site of the Day — CSS Design Awards Best UI — European Design Awards uži izbor',
    nextProject: 'Sljedeći\nprojekat',
  },
  research: {
    title: ['Uvijek', 'Istražujemo'],
    support: 'Šta se oblikuje i\nšta se može oblikovati',
  },
  about: {
    title: ['O nama', 'Nova Forma'],
    support: 'Stvoreno za stvari i ljude\nkoji traže novu formu',
    concept: 'Koncept',
    statement: 'Vjerujemo da svaka ideja već ima oblik.\nNaš posao je da ga pronađemo, osvijetlimo\ni pustimo ljude unutra.',
    conceptBody:
      'Nova Forma je studio dizajnera, inženjera i pripovjedača koji rade između fizičkog i digitalnog. Počeli smo u maloj sobi iznad jedne radionice na Baščaršiji, okruženi bakrom, kamenom i strpljenjem. To naslijeđe nas i danas vodi: prototipe pravimo rukom, testiramo svjetlom i projekat smatramo završenim tek kad djeluje neizbježno. Danas radimo s brendovima, kulturnim institucijama i gradovima širom svijeta.',
    logoLead:
      'Logo se preoblikuje svake ponoći, na osnovu godine, mjeseca i datuma. Nosi ideju Nove Forme da ništa što pravimo ne stoji mirno, baš kao ni ljudi i mjesta za koje dizajniramo.',
    nextForm: 'Sljedeća forma',
    formThe: ['Forma', 'Svjetlo', 'Prostor', 'Pokret', 'Sjećanje'],
    team: 'Tim',
    collaborator: 'Saradnik',
    open: 'Otvori',
    close: 'Zatvori',
    gallery: 'Galerija',
    join: 'Pridruži se',
    joinBody:
      'Uvijek tražimo radoznale ljude koji vole praviti stvari rukama i glavom. Ako voliš svjetlo, prostor i spori zanat, piši nam i pošalji nekoliko projekata na koje si ponosan/na.',
    entry: 'Prijava',
    roles: ['Dizajner prostora', '3D umjetnik', 'Kreativni developer', 'Producent'],
    profile: 'Profil',
    profileRows: [
      ['Naziv firme', 'Nova Forma d.o.o.'],
      ['Zastupnik', 'Amar Hadžić'],
      ['Ured', 'Ferhadija 12, 71000 Sarajevo\nBosna i Hercegovina'],
      ['Oblasti', 'Dizajn prostora, brending, 3D, film, digitalna iskustva, istraživanje'],
      ['Klijenti', 'Maison Aura, Vedra Watches, Pulse Labs, Hotel Bašta, BH Aviation Museum'],
    ],
    partners: 'Partneri',
    partner: 'Atelier Svjetlo',
    partnerDesc: 'Partner za inženjering svjetla',
  },
}

export const dicts: Record<Locale, Dict> = { en, bs }
export const getDict = (l: Locale) => dicts[l]
