import type { Locale } from '@/lib/i18n'

const en = {
  nav: { home: 'Home', project: 'Project', research: 'Research', about: 'About' },
  menu: 'Menu',
  city: 'Sarajevo',
  studio: 'Nova Forma',
  home: {
    title: ['Shaping', 'The Form', 'of Light'],
    lead: 'Nova Forma designs and hand-makes chandeliers and lighting for hotels, restaurants, homes and museums. Atelier in Sarajevo, projects worldwide.',
    projects: 'Projects',
    whatWeDo: 'What we do',
    statement: 'Nova Forma is a lighting atelier based in Sarajevo.\nWe design, make and sell chandeliers and lighting.',
    aboutUs: 'About us',
    featured: 'Featured project\nand research',
    viewAll: 'View all project',
  },
  territory: 'Our craft\nand clients',
  fieldsA: ['Chandeliers', 'Pendants', 'Wall lights', 'Lighting design', 'Glassblowing', 'Brasswork', 'Installation'],
  fieldsB: ['Hotels', 'Restaurants', 'Residences', 'Museums', 'Galleries', 'Offices', 'Heritage', 'Gardens', 'Retail'],
  footer: {
    tagline: 'Atelier in Sarajevo\nprojects worldwide',
    backToTop: 'Back to top',
    cta: 'Get *in* touch',
    social: 'Instagram',
    dark: 'Dark mode',
    light: 'Light mode',
  },
  archive: { drag: '(Drag)', swipe: '(Swipe)' },
  cursor: { drag: 'Drag', explore: 'Explore', next: 'Next', click: 'Click' },
  detail: {
    back: 'Back',
    scroll: '(Scroll)',
    next: 'Next',
    client: 'Client',
    year: 'Year',
    category: 'Category',
    link: 'Enquiry',
    visit: 'Request a quote',
    shiftThe: 'In numbers',
    credits: 'Credits',
    awards: 'Awards',
    awardsText: 'Lighting Design Awards — Hospitality Winner 2026 · Red Dot Product Design — Opal Series · darc awards — Shortlist',
    nextProject: 'Next\nproject',
  },
  research: {
    title: ['Always', 'Testing'],
    support: 'Glass, brass, linen and light\nstudied in our own workshop',
  },
  about: {
    title: ['About', 'Nova Forma'],
    support: 'A lighting atelier where every piece\nis designed and made by hand',
    concept: 'Concept',
    statement: 'We believe light is a material.\nIt can be blown, cast, pleated and polished,\njust like glass, brass and linen.',
    conceptBody:
      'Nova Forma was founded in 2019 by lighting designer Amar Hadžić in a former copper workshop in Baščaršija. Today twelve people work under one roof: designers, glassblowers, metalworkers and lighting engineers. We make custom chandeliers and lamps for hotels, restaurants, homes and museums, and we plan the complete lighting of the spaces they hang in. Everything we sell is made in Sarajevo and installed by our own team.',
    logoLead:
      'Our logo re-forms itself every midnight, based on the year, month and date, the way daylight changes a room from hour to hour. No two days look the same, just like no two hand-blown shades.',
    nextForm: 'Next form',
    formThe: ['Glass', 'Brass', 'Linen', 'Copper', 'Alabaster'],
    team: 'Team',
    collaborator: 'Partner',
    open: 'Open',
    close: 'Close',
    gallery: 'Atelier',
    join: 'Join us',
    joinBody:
      'We are always looking for patient hands and curious eyes. If you work with glass, metal or light and want to see your work hanging in real spaces, send us a few pieces you are proud of.',
    entry: 'Apply',
    roles: ['Glassblower', 'Metalworker', 'Lighting designer', 'Project manager'],
    profile: 'Profile',
    profileRows: [
      ['Company name', 'Nova Forma d.o.o.'],
      ['Founder', 'Amar Hadžić'],
      ['Atelier & showroom', 'Kazandžiluk 12, 71000 Sarajevo\nBosnia and Herzegovina'],
      ['What we make', 'Custom chandeliers, pendants, wall and table lamps, lighting design and installation'],
      ['Clients', 'Hotel Bašta, Galerija Ars, Restoran Bakar, Unitas Tower, private residences'],
    ],
    partners: 'Partners',
    partner: 'Staklara Kreševo',
    partnerDesc: 'Glass furnace partner since 2019',
  },
}

export type Dict = typeof en

const bs: Dict = {
  nav: { home: 'Početna', project: 'Projekti', research: 'Istraživanje', about: 'O nama' },
  menu: 'Meni',
  city: 'Sarajevo',
  studio: 'Nova Forma',
  home: {
    title: ['Oblikujemo', 'Formu', 'Svjetla'],
    lead: 'Nova Forma dizajnira i ručno izrađuje lustere i rasvjetu za hotele, restorane, domove i muzeje. Atelje u Sarajevu, projekti širom svijeta.',
    projects: 'Projekti',
    whatWeDo: 'Šta radimo',
    statement: 'Nova Forma je atelje za svjetlo iz Sarajeva.\nDizajniramo, izrađujemo i prodajemo lustere i rasvjetu.',
    aboutUs: 'O nama',
    featured: 'Izdvojeni projekti\ni istraživanja',
    viewAll: 'Svi projekti',
  },
  territory: 'Naš zanat\ni klijenti',
  fieldsA: ['Lusteri', 'Visilice', 'Zidne lampe', 'Dizajn rasvjete', 'Duvanje stakla', 'Mesing', 'Montaža'],
  fieldsB: ['Hoteli', 'Restorani', 'Domovi', 'Muzeji', 'Galerije', 'Uredi', 'Naslijeđe', 'Vrtovi', 'Radnje'],
  footer: {
    tagline: 'Atelje u Sarajevu\nprojekti širom svijeta',
    backToTop: 'Na vrh',
    cta: 'Javite *nam* se',
    social: 'Instagram',
    dark: 'Tamna tema',
    light: 'Svijetla tema',
  },
  archive: { drag: '(Prevuci)', swipe: '(Prevuci)' },
  cursor: { drag: 'Prevuci', explore: 'Istraži', next: 'Dalje', click: 'Klik' },
  detail: {
    back: 'Nazad',
    scroll: '(Skrolaj)',
    next: 'Dalje',
    client: 'Klijent',
    year: 'Godina',
    category: 'Kategorija',
    link: 'Upit',
    visit: 'Zatraži ponudu',
    shiftThe: 'U brojkama',
    credits: 'Zasluge',
    awards: 'Nagrade',
    awardsText: 'Lighting Design Awards — pobjednik Hospitality 2026 · Red Dot Product Design — Opal serija · darc awards — uži izbor',
    nextProject: 'Sljedeći\nprojekat',
  },
  research: {
    title: ['Uvijek', 'Testiramo'],
    support: 'Staklo, mesing, lan i svjetlo\nproučeni u našoj radionici',
  },
  about: {
    title: ['O nama', 'Nova Forma'],
    support: 'Atelje za svjetlo u kojem je svaki komad\ndizajniran i napravljen rukom',
    concept: 'Koncept',
    statement: 'Vjerujemo da je svjetlo materijal.\nMože se duvati, liti, plisirati i polirati,\nbaš kao staklo, mesing i lan.',
    conceptBody:
      'Novu Formu je 2019. osnovao dizajner svjetla Amar Hadžić u nekadašnjoj kazandžijskoj radionici na Baščaršiji. Danas pod jednim krovom radi dvanaest ljudi: dizajneri, staklari, metalci i inženjeri rasvjete. Pravimo lustere i lampe po mjeri za hotele, restorane, domove i muzeje, i planiramo kompletnu rasvjetu prostora u kojima vise. Sve što prodajemo napravljeno je u Sarajevu i montira ga naš tim.',
    logoLead:
      'Naš logo se preoblikuje svake ponoći, na osnovu godine, mjeseca i datuma, kao što dnevno svjetlo mijenja sobu iz sata u sat. Nijedan dan ne izgleda isto, baš kao ni dva ručno duvana abažura.',
    nextForm: 'Sljedeća forma',
    formThe: ['Staklo', 'Mesing', 'Lan', 'Bakar', 'Alabaster'],
    team: 'Tim',
    collaborator: 'Partner',
    open: 'Otvori',
    close: 'Zatvori',
    gallery: 'Atelje',
    join: 'Pridruži se',
    joinBody:
      'Uvijek tražimo strpljive ruke i radoznale oči. Ako radiš sa staklom, metalom ili svjetlom i želiš vidjeti svoj rad kako visi u stvarnim prostorima, pošalji nam nekoliko komada na koje si ponosan/na.',
    entry: 'Prijava',
    roles: ['Staklar', 'Metalac', 'Dizajner rasvjete', 'Projekt menadžer'],
    profile: 'Profil',
    profileRows: [
      ['Naziv firme', 'Nova Forma d.o.o.'],
      ['Osnivač', 'Amar Hadžić'],
      ['Atelje i izložbeni salon', 'Kazandžiluk 12, 71000 Sarajevo\nBosna i Hercegovina'],
      ['Šta pravimo', 'Lusteri po mjeri, visilice, zidne i stone lampe, dizajn i montaža rasvjete'],
      ['Klijenti', 'Hotel Bašta, Galerija Ars, Restoran Bakar, Unitas Tower, privatni domovi'],
    ],
    partners: 'Partneri',
    partner: 'Staklara Kreševo',
    partnerDesc: 'Partner za staklarsku peć od 2019.',
  },
}

export const dicts: Record<Locale, Dict> = { en, bs }
export const getDict = (l: Locale) => dicts[l]
